### ISSUE TITLE
After purchasing coins, the cta redirects to the battle with premium match config preset

### ISSUE THREAD

**Issue by makando95** [playt-net/rolling-rick#83]
**Intro**

After the first purchase: I was then told to try out Premium Currency immediately. But then I suddenly had a Solitaire Jack test game as a match configuration and because I clicked on Start so quickly, I played a free game first. As a user I expected something different. It would be cool if you landed directly at the Premium Currency as a match configuration after purchasing.

**AC**

- The CTA after the purchase of coins leads to the battle screen where either the last game played with the lowest premium configuration is selected or, if the last game is not yet unlocked for premium, a random game that is already unlocked for premium is selected.

This CTA: 
![Image](https://github.com/playt-net/rolling-rick/assets/70894426/8b739092-9a57-498c-bb0d-8803c4a2c92f)

**Comment by boredland** [comment]
duplicate/wrong project
